### ISSUE TITLE
Support uploading artifacts newer than a build.

### ISSUE THREAD

**Issue by karataliu** [jenkinsci/windows-azure-storage-plugin#52]
Files match 'list of artifacts to upload' should be checked whether has an update time newer than current build.

This is like what 'Publish Junit test result report' does, which checks only result xml file newer than current build.

Also can provider an option for 'do not fail on empty match', for cases where files exist but older than current build.

**Comment by gavinfish** [comment]
Hi @juniwang ,
I think we should add two more options in advanced settings. One for whether only upload artifacts updated during the build, and the other one for whether fail on empty match.

For archiving feature, do you think we should only archive updated artifacts or all the artifacts when the first options is selected?

**Comment by juniwang** [comment]
Actually team once discussed about the empty match. We believed it should fail or unstable the build. And for archiving feature, the archive is designed to include ALL files. Since it can be downloaded or used in other job/place independently, it should be fully self-contained.  We can upload newer version of individual files because there are already the same files on Azure which make the files on Azure are fully inclusive.

**Comment by gavinfish** [comment]
closing
