### ISSUE TITLE
Add a list operation to list content of storage

### ISSUE THREAD

**Issue by simon-michaud** [jenkinsci/windows-azure-storage-plugin#87]
Having a list operation would enable us to use this plugin in a flow similar to this:
- Upload artifacts
- List artifacts and demand and store it in a file
- Use file as list of available artifacts for entry parameters for download /deploy of artifacts

**Comment by gavinfish** [comment]
Hi @simon-michaud , sorry for the late reply.

Thanks for your suggestions. Indeed you can download artifacts from other builds directly instead of saving them in a file and reading them again. Do we need list and storing artifacts in a file in other situation? Please share your thoughts, thanks.

**Comment by juniwang** [comment]
So per my understanding, what you really need is to be able to list constainers of certain storage account.  Instead of using a file as entry parameter of a Dropdown, why don't you think about using the Azure List Containes API response as an entry parameter? You don't have to setup project B in this way.

And we can update the way you fill up your `containerName` in download job to allow you to input a name OR select one for a dropdown which lists all containers of your storage account.

**Comment by simon-michaud** [comment]
That would be perfect.

**Comment by gavinfish** [comment]
It seems that the problem has been solved. Closing.
